env:
  browser: true
  jest: true
parserOptions:
  project: "./tsconfig.json"
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - prettier
rules:
  consistent-return: 'off'
  no-empty: 'off'
  import/prefer-default-export: 'off'
  jsx-a11y/media-has-caption: 'warn'
  react/react-in-jsx-scope: 'off'
  react/function-component-definition: 'off'
  react/no-unescaped-entities: 'off'
  react/require-default-props: 'off'
  react/jsx-props-no-spreading: 'off'
  react-hooks/exhaustive-deps: 'warn'
  react/no-array-index-key: 'warn'
  jsx-a11y/anchor-is-valid: 'warn'
  '@typescript-eslint/ban-ts-comment': 'warn'
