/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v2.2/films/{id}": {
    /** Данный эндпоинт возвращает базовые данные о фильме. Поле <b>lastSync</b> показывает дату последнего обновления данных. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["Film"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильм не найден */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/seasons": {
    /** Данный эндпоинт возвращает данные о сезонах для сериала. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["SeasonResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/facts": {
    /** Данный эндпоинт возвращает список фактов и ошибок в фильме. <br> type - <b>FACT</b>, обозначает интересный факт о фильме. <br> type - <b>BLOOPER</b>, обозначает ошибку в фильме. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FactResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/distributions": {
    /** Данный эндпоинт возвращает данные о прокате в разных странах. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["DistributionResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/box_office": {
    /** Данный эндпоинт возвращает данные о бюджете и сборах. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["BoxOfficeResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/videos": {
    /** Данный эндпоинт возвращает трейлеры,тизеры,видео для фильма по kinopoisk film id. В данный момент доступно два site:  <br/> <ul><li>YOUTUBE - в этом случае <b>url</b> это просто ссылка на youtube видео.</li><li>KINOPOISK_WIDGET - в этом случае <b>url</b> это ссылка на кинопоиск виджет. Например https://widgets.kinopoisk.ru/discovery/trailer/123573?onlyPlayer=1&autoplay=1&cover=1. Если вы хотите вставить этот виджет на вашу страницу, вы можете сделать следующее:  <br/><br/>&lt;script src=&quot;https://unpkg.com/@ungap/custom-elements-builtin&quot;&gt;&lt;/script&gt;<br/>&lt;script type=&quot;module&quot; src=&quot;https://unpkg.com/x-frame-bypass&quot;&gt;&lt;/script&gt;<br/>&lt;iframe is=&quot;x-frame-bypass&quot; src=&quot;https://widgets.kinopoisk.ru/discovery/trailer/167560?onlyPlayer=1&amp;autoplay=1&amp;cover=1&quot; width=&quot;500&quot; height=&quot;500&quot;&gt;&lt;/iframe&gt;</li></ul> */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["VideoResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/top": {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. */
    get: {
      parameters: {
        query: {
          /** тип топа или коллекции */
          type?:
            | "TOP_250_BEST_FILMS"
            | "TOP_100_POPULAR_FILMS"
            | "TOP_AWAIT_FILMS";
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FilmTopResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Лимит 5 запроса в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/{id}/similars": {
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["RelatedFilmResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.2/films/premieres": {
    /** Данный эндпоинт возвращает список кинопремьер. Например https://www.kinopoisk.ru/premiere/ */
    get: {
      parameters: {
        query: {
          /** год релиза */
          year: number;
          /** месяц релиза */
          month:
            | "JANUARY"
            | "FEBRUARY"
            | "MARCH"
            | "APRIL"
            | "MAY"
            | "JUNE"
            | "JULY"
            | "AUGUST"
            | "SEPTEMBER"
            | "OCTOBER"
            | "NOVEMBER"
            | "DECEMBER";
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["PremiereResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/{id}/frames": {
    /** Данный эндпоинт возвращает кадры из фильма. */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FilmFrameResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Кадры не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/{id}/sequels_and_prequels": {
    /** tbd */
    get: {
      parameters: {
        path: {
          /** kinopoisk film id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FilmSequelsAndPrequelsResponse"][];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильм не найден */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/search-by-keyword": {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. */
    get: {
      parameters: {
        query: {
          /** ключивые слова для поиска */
          keyword: string;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FilmSearchResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/filters": {
    /** Возвращает список id стран и жанров, которые могут быть использованы в /api/v2.1/films/search-by-filters */
    get: {
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FiltersResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/search-by-filters": {
    /** Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. <i>Используй /api/v2.1/films/filters чтобы получить id стран и жанров.</i> */
    get: {
      parameters: {
        query: {
          /** список id стран разделенные запятой. Например <i>country=1,2,3</i> */
          country?: number[];
          /** список id жанров разделенные запятой. Например <i>genre=1,2,3</i> */
          genre?: number[];
          /** сортировка */
          order?: "RATING" | "NUM_VOTE" | "YEAR";
          /** тип фильма */
          type?: "FILM" | "TV_SHOW" | "ALL";
          /** минимальный рейтинг */
          ratingFrom?: number;
          /** максимальный рейтинг */
          ratingTo?: number;
          /** минимальный год */
          yearFrom?: number;
          /** максимальный год */
          yearTo?: number;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["FilmSearchByFiltersResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v2.1/films/releases": {
    /** Данный эндпоинт возвращает список цифровых релизов. Например https://www.kinopoisk.ru/comingsoon/digital/ */
    get: {
      parameters: {
        query: {
          /** год релиза */
          year: number;
          /** месяц релиза */
          month:
            | "JANUARY"
            | "FEBRUARY"
            | "MARCH"
            | "APRIL"
            | "MAY"
            | "JUNE"
            | "JULY"
            | "AUGUST"
            | "SEPTEMBER"
            | "OCTOBER"
            | "NOVEMBER"
            | "DECEMBER";
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["DigitalReleaseResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Фильмы не найдены */
        404: unknown;
        /** Слишком много запросов. Лимит 5 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v1/reviews": {
    /** Возвращает список рецензий с пагинацией. Каждая страница содержит не более чем 20 рецензий. Поле <b>description</b> содержит не полный текст рецензии. Полный текст может быть получен из /api/v1/reviews/details */
    get: {
      parameters: {
        query: {
          /** kinopoisk film id */
          filmId: number;
          /** номер страницы */
          page?: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["ReviewsResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Рецензии не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v1/reviews/details": {
    /** Возвращает полную информацию о рецензии. */
    get: {
      parameters: {
        query: {
          /** kinopoisk review id */
          reviewId: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["ReviewDetailsResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Рецензия не найдена */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v1/staff": {
    get: {
      parameters: {
        query: {
          /** kinopoisk film id */
          filmId: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["StaffResponse"][];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Данные не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
  "/api/v1/staff/{id}": {
    get: {
      parameters: {
        path: {
          /** kinopoisk person id */
          id: number;
        };
      };
      responses: {
        /** Запрос выполнен успешно */
        200: {
          content: {
            "application/json": components["schemas"]["PersonResponse"];
          };
        };
        /** Пустой или неправильный токен */
        401: unknown;
        /** Данные не найдены */
        404: unknown;
        /** Слишком много запросов. Общий лимит - 20 запросов в секунду */
        429: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Film: {
      kinopoiskId: number;
      imdbId: string;
      nameRu: string;
      nameEn: string;
      nameOriginal: string;
      posterUrl: string;
      posterUrlPreview: string;
      reviewsCount: number;
      ratingGoodReview: number;
      ratingGoodReviewVoteCount: number;
      ratingKinopoisk: number;
      ratingKinopoiskVoteCount: number;
      ratingImdb: number;
      ratingImdbVoteCount: number;
      ratingFilmCritics: number;
      ratingFilmCriticsVoteCount: number;
      ratingAwait: number;
      ratingAwaitCount: number;
      ratingRfCritics: number;
      ratingRfCriticsVoteCount: number;
      webUrl: string;
      year: number;
      filmLength: number;
      slogan: string;
      description: string;
      shortDescription: string;
      editorAnnotation: string;
      isTicketsAvailable: boolean;
      productionStatus:
        | "FILMING"
        | "PRE_PRODUCTION"
        | "COMPLETED"
        | "ANNOUNCED"
        | "UNKNOWN"
        | "POST_PRODUCTION";
      type: "FILM" | "VIDEO" | "TV_SERIES" | "MINI_SERIES" | "TV_SHOW";
      ratingMpaa: string;
      ratingAgeLimits: string;
      hasImax: boolean;
      has3D: boolean;
      lastSync: string;
      countries: components["schemas"]["Country"][];
      genres: components["schemas"]["Genre"][];
      startYear: number;
      endYear: number;
      serial?: boolean;
      shortFilm?: boolean;
      completed?: boolean;
    };
    SeasonResponse: {
      total: number;
      items: components["schemas"]["Season"][];
    };
    FactResponse: {
      total: number;
      items: components["schemas"]["Fact"][];
    };
    DistributionResponse: {
      total: number;
      items: components["schemas"]["Distribution"][];
    };
    BoxOfficeResponse: {
      total: number;
      items: components["schemas"]["BoxOffice"][];
    };
    Fact: {
      text: string;
      type: "FACT" | "BLOOPER";
      spoiler: boolean;
    };
    BoxOffice: {
      type: string;
      amount: number;
      currencyCode: string;
      name: string;
      symbol: string;
    };
    Distribution: {
      type: "LOCAL" | "COUNTRY_SPECIFIC" | "PREMIERE" | "ALL" | "WORLD_PREMIER";
      subType: "CINEMA" | "DVD" | "DIGITAL" | "BLURAY";
      date: string;
      reRelease: boolean;
      country: components["schemas"]["Country"];
      companies: components["schemas"]["Company"][];
    };
    Company: {
      name: string;
    };
    Season: {
      number: number;
      episodes: components["schemas"]["Episode"][];
    };
    Episode: {
      seasonNumber: number;
      episodeNumber: number;
      nameRu: string;
      nameEn: string;
      synopsis: string;
      releaseDate: string;
    };
    Country: {
      country: string;
    };
    Genre: {
      genre: string;
    };
    FiltersResponse: {
      genres: components["schemas"]["FiltersResponse_genres"][];
      countries: components["schemas"]["FiltersResponse_countries"][];
    };
    FilmSearchResponse: {
      keyword: string;
      pagesCount: number;
      searchFilmsCountResult: number;
      films: components["schemas"]["FilmSearchResponse_films"][];
    };
    FilmSearchByFiltersResponse: {
      pagesCount: number;
      films: components["schemas"]["FilmSearchResponse_films"][];
    };
    FilmSequelsAndPrequelsResponse: {
      filmId: number;
      nameRu: string;
      nameEn: string;
      nameOriginal: string;
      posterUrl: string;
      posterUrlPreview: string;
      relationType: "SEQUEL" | "PREQUEL" | "REMAKE" | "UNKNOWN";
    };
    RelatedFilmResponse: {
      total: number;
      items: components["schemas"]["RelatedFilmResponse_items"][];
    };
    FilmTopResponse: {
      pagesCount: number;
      films: components["schemas"]["FilmTopResponse_films"][];
    };
    ReviewsResponse: {
      page: number;
      filmId: number;
      reviewAllCount: number;
      reviewAllPositiveRatio: string;
      reviewPositiveCount: number;
      reviewNegativeCount: number;
      reviewNeutralCount: number;
      pagesCount: number;
      reviews: components["schemas"]["ReviewsResponse_reviews"][];
    };
    ReviewDetailsResponse: {
      reviewId: number;
      reviewType: "POSITIVE" | "NEGATIVE" | "NEUTRAL" | "UNKNOWN";
      reviewData: string;
      userPositiveRating: number;
      userNegativeRating: number;
      reviewAutor: string;
      reviewTitle: string;
      reviewDescription: number;
    };
    StaffResponse: {
      staffId: number;
      nameRu: string;
      nameEn: string;
      posterUrl: string;
      professionText: string;
      professionKey:
        | "WRITER"
        | "OPERATOR"
        | "EDITOR"
        | "COMPOSER"
        | "PRODUCER_USSR"
        | "TRANSLATOR"
        | "DIRECTOR"
        | "DESIGN"
        | "PRODUCER"
        | "ACTOR"
        | "VOICE_DIRECTOR"
        | "UNKNOWN";
    };
    PersonResponse: {
      personId: number;
      webUrl: string;
      nameRu: string;
      nameEn: string;
      sex: "MALE" | "FEMALE";
      posterUrl: string;
      growth: string;
      birthday: string;
      death: string;
      age: number;
      birthplace: string;
      deathplace: string;
      hasAwards: number;
      profession: string;
      facts: string[];
      spouses: components["schemas"]["PersonResponse_spouses"][];
      films: components["schemas"]["PersonResponse_films"][];
    };
    FilmFrameResponse: {
      frames: components["schemas"]["FilmFrameResponse_frames"][];
    };
    PremiereResponse: {
      total: number;
      items: components["schemas"]["PremiereResponseItem"][];
    };
    PremiereResponseItem: {
      kinopoiskId: number;
      nameRu: string;
      nameEn: string;
      year: number;
      posterUrl: string;
      posterUrlPreview: string;
      countries: components["schemas"]["Country"][];
      genres: components["schemas"]["Genre"][];
      duration: number;
      premiereRu: string;
    };
    DigitalReleaseResponse: {
      page: number;
      total: number;
      releases: components["schemas"]["DigitalReleaseItem"][];
    };
    DigitalReleaseItem: {
      filmId: number;
      nameRu: string;
      nameEn: string;
      year: number;
      posterUrl: string;
      posterUrlPreview: string;
      countries: components["schemas"]["Country"][];
      genres: components["schemas"]["Genre"][];
      rating: number;
      ratingVoteCount: number;
      expectationsRating: number;
      expectationsRatingVoteCount: number;
      duration: number;
      releaseDate: string;
    };
    VideoResponse: {
      total: number;
      items: components["schemas"]["VideoResponse_items"][];
    };
    FiltersResponse_genres: {
      id?: number;
      genre?: string;
    };
    FiltersResponse_countries: {
      id?: number;
      country?: string;
    };
    FilmSearchResponse_films: {
      filmId?: number;
      nameRu?: string;
      nameEn?: string;
      type?: "FILM" | "TV_SHOW" | "UNKNOWN";
      year?: string;
      description?: string;
      filmLength?: string;
      countries?: components["schemas"]["Country"][];
      genres?: components["schemas"]["Genre"][];
      rating?: string;
      ratingVoteCount?: number;
      posterUrl?: string;
      posterUrlPreview?: string;
    };
    RelatedFilmResponse_items: {
      filmId?: number;
      nameRu?: string;
      nameEn?: string;
      nameOriginal?: string;
      posterUrl?: string;
      posterUrlPreview?: string;
      relationType?: "SIMILAR";
    };
    FilmTopResponse_films: {
      filmId?: number;
      nameRu?: string;
      nameEn?: string;
      year?: string;
      filmLength?: string;
      countries?: components["schemas"]["Country"][];
      genres?: components["schemas"]["Genre"][];
      rating?: number;
      ratingVoteCount?: number;
      posterUrl?: string;
      posterUrlPreview?: string;
    };
    ReviewsResponse_reviews: {
      reviewId?: number;
      reviewType?: "POSITIVE" | "NEGATIVE" | "NEUTRAL" | "UNKNOWN";
      reviewData?: string;
      userPositiveRating?: string;
      userNegativeRating?: string;
      reviewAutor?: string;
      reviewTitle?: string;
      reviewDescription?: number;
    };
    PersonResponse_spouses: {
      personId?: number;
      name?: string;
      divorced?: boolean;
      divorcedReason?: string;
      sex?: "MALE" | "FEMALE";
      children?: number;
      webUrl?: string;
      relation?: string;
    };
    PersonResponse_films: {
      filmId?: number;
      nameRu?: string;
      nameEn?: string;
      rating?: string;
      general?: boolean;
      description?: string;
      professionKey?:
        | "WRITER"
        | "OPERATOR"
        | "EDITOR"
        | "COMPOSER"
        | "PRODUCER_USSR"
        | "HIMSELF"
        | "HERSELF"
        | "HRONO_TITR_MALE"
        | "HRONO_TITR_FEMALE"
        | "TRANSLATOR"
        | "DIRECTOR"
        | "DESIGN"
        | "PRODUCER"
        | "ACTOR"
        | "VOICE_DIRECTOR"
        | "UNKNOWN";
    };
    FilmFrameResponse_frames: {
      image?: string;
      preview?: string;
    };
    VideoResponse_items: {
      url?: string;
      name?: string;
      site?: "YOUTUBE" | "KINOPOISK_WIDGET" | "UNKNOWN";
    };
  };
}

export interface operations {}
