/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/honey-votes/auth/refresh-token": {
    post: operations["AuthController_refreshToken"];
  };
  "/api/honey-votes/users": {
    get: operations["UsersController_getUserByLogin"];
  };
  "/api/honey-votes/users/me": {
    get: operations["UsersController_me"];
  };
  "/api/honey-votes/users/me/roles": {
    get: operations["UsersController_getUserRoles"];
  };
  "/api/honey-votes/voting": {
    get: operations["VotingController_getVotingList"];
    post: operations["VotingController_addVoting"];
  };
  "/api/honey-votes/voting/{votingId}": {
    get: operations["VotingController_getVoting"];
    put: operations["VotingController_updateVoting"];
    delete: operations["VotingController_removeVoting"];
  };
  "/api/honey-votes/voting-options": {
    post: operations["VotingOptionsController_addVotingOption"];
  };
  "/api/honey-votes/voting-options/{votingOptionId}": {
    delete: operations["VotingOptionsController_removeVotingOption"];
  };
  "/api/honey-votes/votes": {
    post: operations["VotesController_addVote"];
    delete: operations["VotesController_removeVote"];
  };
  "/api/honey-votes/chat-votes": {
    post: operations["ChatVotesController_addChatVoting"];
  };
  "/api/honey-votes/chat-votes/{chatVotingId}": {
    put: operations["ChatVotesController_updateChatVoting"];
    delete: operations["ChatVotesController_removeChatVoting"];
  };
  "/api/honey-votes/chat-votes/{chatVotingId}/clear": {
    post: operations["ChatVotesController_clearChatVotes"];
  };
}

export interface components {
  schemas: {
    RefreshTokenDto: {
      refreshToken: string;
    };
    RefreshTokenResponse: {
      accessToken: string;
      refreshToken: string;
    };
    User: {
      id: string;
      login: string;
      displayName: string;
      avatarUrl: string;
      areTokensValid: boolean;
      createdAt: string;
      updatedAt: string;
    };
    UserRoles: {
      isEditor: boolean | null;
      isMod: boolean | null;
      isVip: boolean | null;
      isSub: boolean | null;
      isFollower: boolean | null;
      minutesFollowed: number | null;
      subTier: number | null;
    };
    Vote: {
      id: number;
      authorId: string;
      votingId: number;
      votingOptionId: number;
      value: number;
      createdAt: string;
      updatedAt: string;
    };
    VotingPermissionsDefault: {
      canVote: boolean;
      canAddOptions: boolean;
    };
    VotingPermissionsSubscriber: {
      canVote: boolean;
      canAddOptions: boolean;
      subTierRequiredToVote: number;
      subTierRequiredToAddOptions: number;
    };
    VotingPermissionsFollower: {
      canVote: boolean;
      canAddOptions: boolean;
      minutesToFollowRequiredToVote: number;
      minutesToFollowRequiredToAddOptions: number;
    };
    VotingPermissions: {
      mod: components["schemas"]["VotingPermissionsDefault"];
      vip: components["schemas"]["VotingPermissionsDefault"];
      sub: components["schemas"]["VotingPermissionsSubscriber"];
      follower: components["schemas"]["VotingPermissionsFollower"];
      viewer: components["schemas"]["VotingPermissionsDefault"];
    };
    Voting: {
      id: number;
      broadcasterId: string;
      title?: string;
      description?: string;
      canManageVotes: boolean;
      canManageVotingOptions: boolean;
      permissions: components["schemas"]["VotingPermissions"];
      allowedVotingOptionTypes: ("kinopoiskMovie" | "igdbGame" | "custom")[];
      votingOptionsLimit: number;
      createdAt: string;
      updatedAt: string;
    };
    CreateVotingDto: {
      title?: string;
      description?: string;
      canManageVotes?: boolean;
      canManageVotingOptions?: boolean;
      permissions?: components["schemas"]["VotingPermissions"];
      allowedVotingOptionTypes?: ("kinopoiskMovie" | "igdbGame" | "custom")[];
      votingOptionsLimit?: number;
      channelId: string;
    };
    UpdateVotingDto: {
      title?: string;
      description?: string;
      canManageVotes?: boolean;
      canManageVotingOptions?: boolean;
      permissions?: components["schemas"]["VotingPermissions"];
      allowedVotingOptionTypes?: ("kinopoiskMovie" | "igdbGame" | "custom")[];
      votingOptionsLimit?: number;
    };
    VotingOptionKinopoiskMovie: {
      id: number;
    };
    VotingOptionIgdbGame: {
      slug: string;
    };
    VotingOptionCustom: {
      title: string;
      description?: string;
    };
    CreateVotingOptionDto: {
      votingId: number;
      type: string;
      kinopoiskMovie?: components["schemas"]["VotingOptionKinopoiskMovie"];
      igdbGame?: components["schemas"]["VotingOptionIgdbGame"];
      custom?: components["schemas"]["VotingOptionCustom"];
    };
    VotingOption: {
      id: number;
      authorId: string;
      authorLogin: string;
      votingId: number;
      fullVotesValue: number;
      cardId?: string;
      cardTitle: string;
      cardSubtitle?: string;
      cardDescription?: string;
      cardImageUrl?: string;
      cardUrl?: string;
      createdAt: string;
      updatedAt: string;
    };
    CreateVoteDto: {
      votingOptionId: number;
    };
    DeleteVoteDto: {
      votingOptionId: number;
    };
    ChatVotingPermissions: {
      viewer: boolean;
      sub: boolean;
      mod: boolean;
      vip: boolean;
      subMonthsRequired: number;
      subTierRequired: number;
    };
    ChatVotingCommands: {
      vote: string;
      clearVotes: string;
    };
    CreateChatVotingDto: {
      permissions?: components["schemas"]["ChatVotingPermissions"];
      listening?: boolean;
      commands?: components["schemas"]["ChatVotingCommands"];
      broadcasterId: string;
    };
    ChatVote: {
      chatVotingId: string;
      userId: string;
      userName: string;
      tags: { [key: string]: any };
      content: string;
      createdAt: string;
      updatedAt: string;
    };
    ChatVoting: {
      broadcasterId: string;
      permissions: components["schemas"]["ChatVotingPermissions"];
      listening: boolean;
      commands: components["schemas"]["ChatVotingCommands"];
      createdAt: string;
      updatedAt: string;
    };
    UpdateChatVotingDto: {
      permissions?: components["schemas"]["ChatVotingPermissions"];
      listening?: boolean;
      commands?: components["schemas"]["ChatVotingCommands"];
    };
  };
}

export interface operations {
  AuthController_refreshToken: {
    parameters: {};
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["RefreshTokenResponse"];
        };
      };
      /** Bad Request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshTokenDto"];
      };
    };
  };
  UsersController_getUserByLogin: {
    parameters: {
      query: {
        login?: string;
        id?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Not found */
      404: unknown;
    };
  };
  UsersController_me: {
    parameters: {};
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** Unauthorized */
      401: unknown;
    };
  };
  UsersController_getUserRoles: {
    parameters: {
      query: {
        login?: string;
        id?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserRoles"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Not found */
      404: unknown;
    };
  };
  VotingController_getVotingList: {
    parameters: {
      query: {
        channelId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Voting"][];
        };
      };
    };
  };
  VotingController_addVoting: {
    parameters: {};
    responses: {
      /** Created */
      201: {
        content: {
          "application/json": components["schemas"]["Voting"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVotingDto"];
      };
    };
  };
  VotingController_getVoting: {
    parameters: {
      path: {
        votingId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["Voting"];
        };
      };
      /** Not found */
      404: unknown;
    };
  };
  VotingController_updateVoting: {
    parameters: {
      path: {
        votingId: number;
      };
    };
    responses: {
      /** Created */
      201: {
        content: {
          "application/json": components["schemas"]["Voting"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateVotingDto"];
      };
    };
  };
  VotingController_removeVoting: {
    parameters: {
      path: {
        votingId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  VotingOptionsController_addVotingOption: {
    parameters: {};
    responses: {
      /** Created */
      201: {
        content: {
          "application/json": components["schemas"]["VotingOption"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVotingOptionDto"];
      };
    };
  };
  VotingOptionsController_removeVotingOption: {
    parameters: {
      path: {
        votingOptionId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  VotesController_addVote: {
    parameters: {};
    responses: {
      /** Created */
      201: unknown;
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVoteDto"];
      };
    };
  };
  VotesController_removeVote: {
    parameters: {};
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteVoteDto"];
      };
    };
  };
  ChatVotesController_addChatVoting: {
    parameters: {};
    responses: {
      /** Created */
      201: {
        content: {
          "application/json": components["schemas"]["ChatVoting"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateChatVotingDto"];
      };
    };
  };
  ChatVotesController_updateChatVoting: {
    parameters: {
      path: {
        chatVotingId: string;
      };
    };
    responses: {
      /** Created */
      201: {
        content: {
          "application/json": components["schemas"]["ChatVoting"];
        };
      };
      /** Bad request */
      400: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateChatVotingDto"];
      };
    };
  };
  ChatVotesController_removeChatVoting: {
    parameters: {
      path: {
        chatVotingId: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
  ChatVotesController_clearChatVotes: {
    parameters: {
      path: {
        chatVotingId: string;
      };
    };
    responses: {
      /** OK */
      200: unknown;
      /** Unauthorized */
      401: unknown;
      /** Forbidden */
      403: unknown;
    };
  };
}
